### ISSUE TITLE
Incorrect precendence of the `NOT` operator

### ISSUE THREAD

**Issue by jchros** [usagi-coffee/tree-sitter-abl#2]
In [`test/corpus/basic.txt`](https://github.com/usagi-coffee/tree-sitter-abl/blob/5bd2e1ca98d7d8f417a102c4323a52eb19faab32/test/corpus/basic.txt#L137), the expected output of `z = NOT y > 5.` is incorrectly defined as:

```
(variable_assignment
  (assignment
    (identifier)
    (expression
      (comparison
        (expression
          (unary_expression
            (expression
              (identifier))))
        (comparator)
        (expression
          (number_literal)))))
  (terminator))
```

As if it were equivalent to `z = ((NOT y) > 5).`, but OpenEdge ABL interprets this as being equivalent to `z = (NOT (y > 5)).`.

The issue stems from the fact that the `NOT` operator is defined as having a higher precedence than the comparison operator in grammar.js, contrary to [the precedence table](https://docs.progress.com/bundle/openedge-abl-reference-117/page/Expression.html#Expression__abl-operator-precedence_GDK2CR2669446) given in [the ABL reference](https://docs.progress.com/bundle/openedge-abl-reference-117/page/Expression.html).

The same issue occurs in the ["FIND FIRST (no terminator) statement"](https://github.com/usagi-coffee/tree-sitter-abl/blob/5bd2e1ca98d7d8f417a102c4323a52eb19faab32/test/corpus/basic.txt#L747-L769) and the ["TERNARY EXPRESSION (parenthesised) statement"](https://github.com/usagi-coffee/tree-sitter-abl/blob/5bd2e1ca98d7d8f417a102c4323a52eb19faab32/test/corpus/basic.txt#L834-L851) test cases.

**Comment by jkbz64** [comment]
Nice catch, thanks, it should be fixed in ffae5dd74b94c36bff6f4f4ab45d86b68b6e99a2
Reopen if it's still broken
