### ISSUE TITLE
Incorrect parsing

### ISSUE THREAD

**Issue by PauliusKu** [usagi-coffee/tree-sitter-abl#28]
In this statement it picks "Order" as OR
![image](https://github.com/usagi-coffee/tree-sitter-abl/assets/36190136/e72334de-f77a-439a-97ea-16d7907d9334)

![image](https://github.com/usagi-coffee/tree-sitter-abl/assets/36190136/5ce9b923-d77b-465f-a2ba-8e0188c1f34a)

**Comment by jkbz64** [comment]
This one is tricky... might take me a while to fix that

**Comment by jkbz64** [comment]
I have found dumb workaround that got deployed in 0.0.13, going to keep that open to remind myself to fix that properly in future.
