### ISSUE TITLE
Error for comment with "//"

### ISSUE THREAD

**Issue by PauliusKu** [usagi-coffee/tree-sitter-abl#30]
Currently, parser does not understand comments defined using **//**
![image](https://github.com/usagi-coffee/tree-sitter-abl/assets/36190136/7998bf20-86f2-4405-8f03-26d926002b42)

**Comment by jkbz64** [comment]
Oops, I was using some ancient 10.2b progress version that did not support single line comments so I was unaware they added that (just recently migrated to 11.7 and it seems it compiles there, lol)

**Comment by PauliusKu** [comment]
Sounds antient, 11.7 will be retired next year, so better start moving to 12.x :D
Thanks for the fix.
