### ISSUE TITLE
Parentheses are not working

### ISSUE THREAD

**Issue by PauliusKu** [usagi-coffee/tree-sitter-abl#35]
![image](https://github.com/usagi-coffee/tree-sitter-abl/assets/36190136/7e7ee154-9494-4bc1-a951-effd05f40301)

**Comment by jkbz64** [comment]
Your code does not compile for me on 10.2b and 11.7, is that 12.7 thing? Looks like illegal expression, shouldn't there be `then do:` instead of straight up `:`?

**Comment by PauliusKu** [comment]
Yes, sorry, we made a mistake, it does not compile :)
