### ISSUE TITLE
Error on this method.

### ISSUE THREAD

**Issue by PauliusKu** [usagi-coffee/tree-sitter-abl#39]
![image](https://github.com/usagi-coffee/tree-sitter-abl/assets/36190136/fa2fe480-823d-4c19-a9cf-c08c21c2201e)

![image](https://github.com/usagi-coffee/tree-sitter-abl/assets/36190136/b1d73e99-c99a-4ba5-9d4c-f149dd2ff095)

Code is from https://docs.progress.com/bundle/openedge-oo-abl-develop-applications-117/page/Sample-classes.html

**Comment by jkbz64** [comment]
This issue stems from unparsed custom setter method implementation above this method, not this method itself.
