### ISSUE TITLE
Can't use logic operators in expressions

### ISSUE THREAD

**Issue by jchros** [usagi-coffee/tree-sitter-abl#5]
The following code fails to parse:

```abl
x = YES AND NO.
y = YES OR NO.
```

Tree-sitter generates the following AST:

```
(source_code
  (statement
    (variable_assignment
      (assignment
        (identifier)
        (ERROR
          (expression
            (boolean_expression)))
        (expression
          (boolean_expression)))
      (terminator)))
  (statement
    (variable_assignment
      (assignment
        (identifier)
        (ERROR
          (expression
            (boolean_expression)))
        (expression
          (boolean_expression)))
      (terminator))))
```

**Comment by jkbz64** [comment]
Should work in https://github.com/usagi-coffee/tree-sitter-abl/commit/c995534226e1326c8f4083e7bb50c844f560e948 
Still not sure how to handle logical expressions and find conditions, for if's it should use logical expressions instead of conditions, right now it's inconsistent...

**Comment by jkbz64** [comment]
Also doing more than one logical expression e.g `X AND Y AND Z` nests expressions  `(logical expression (expression) (logical_operator) (expression (logical expression(` should it be flattened to `(expression) (logical_operator) (expression) (logical_operator) (expression)` instead?

**Comment by jchros** [comment]
I think that the nesting is desirable since that's how it's actually parsed by OpenEdge ABL. Flattening the tree would be akin to doing tokenization without parsing.

**Comment by jchros** [comment]
One thing that make the tree less heavy would be to hide some rules which are just "choice" rules (e.g. the `expression` rule which is really just a grouping of other rules that occur in many places and which only ever holds one node).  I could work on that if you want.

**Comment by jkbz64** [comment]
Frankly I'm new to tree-sitter, this was my first attempt at creating a parser and don't know how to do it properly, just based the parser on other projects, how would that work? Is there a specific tree-sitter feature to unwrap rules?

**Comment by jkbz64** [comment]
I think I get it, it's the `inline` feature, yeah go ahead if you want to do that.

**Comment by jchros** [comment]
> Frankly I'm new to tree-sitter, this was my first attempt at creating a parser and don't know how to do it properly, just based the parser on other projects, how would that work? Is there a specific tree-sitter feature to unwrap rules?

You can [hide a rule](https://tree-sitter.github.io/tree-sitter/creating-parsers#hiding-rules) by putting an underscore in front of its name; it'll be known by the parser and the `grammar.json` file but it won't show up in `node-types.json` or the generated syntax tree and it won't be accessible through queries, making the tree easier to deal with.

In addition to this, you can put these hidden rules into the grammar's `supertypes` so that tools that our grammar can be aware of them [through the _node types_ file](https://tree-sitter.github.io/tree-sitter/using-parsers#static-node-types).

> I think I get it, it's the inline feature, yeah go ahead if you want to do that.

The `inline` features makes copies of the rule's contents which increases the size of the parser so I don't think it's desirable.
