### ISSUE TITLE
Keyword TABLE has error in method parameter

### ISSUE THREAD

**Issue by PauliusKu** [usagi-coffee/tree-sitter-abl#50]
![image](https://github.com/user-attachments/assets/ec422a8c-7eec-4c04-a1a8-41dff1255936)

**Comment by jkbz64** [comment]
the image does not load for me, please paste code or provide link to the docs

**Comment by eglekaz** [comment]
Code in the screenshot:
`PersonData:GetById(id, output table ttPerson by-reference).`
There is an error on TABLE keyword here.

**Comment by eglekaz** [comment]
In Method Call it works now, but the same issue is still in method definition. 
Example:
```
method public int csvFileToTempTable(pcFilePath as char, pcSeparator as char,
                                        output table-handle phOutputTable):
```
