### ISSUE TITLE
Parameters of external procedure call are not parsed

### ISSUE THREAD

**Issue by eglekaz** [usagi-coffee/tree-sitter-abl#65]
Example:
`run getMyNumber.p(piFirstNum, piSecNum).`

Calls for internal procedures are being parsed correctly.

Reference:
https://documentation.progress.com/output/ua/OpenEdge_latest/pdsoe/PLUGINS_ROOT/com.openedge.pdt.langref.help/rfi1424920323961.html

**Comment by jkbz64** [comment]
If you see abl_statement node in the AST output it means the statement is simply not implemented yet, abl_statement node is just a filler to make more code "parsable" and it is meant to be deleted somewhere along the line if the parser manages to implement every statement (press x to doubt)

**Comment by eglekaz** [comment]
Thank you for explanation!
These errors do not break our logic, so I will close this issue for now.

**Comment by jkbz64** [comment]
Nah, it's fine to reopen this issue, it's that this issue is not about parameters, it's more "Run procedure is not yet implemented".
