### ISSUE TITLE
Version 0.0.39 does not recognize else if statement

### ISSUE THREAD

**Issue by eglekaz** [usagi-coffee/tree-sitter-abl#81]
After last version our tests are showing that else_if_statement is not parsed correctly, which breaks our formatting.
Here is an example:
```
if a = b then message a.
else if b = 1 then message 1.
else if b = 2 then message 2.
```

**Comment by jkbz64** [comment]
It has been merged into `else_statement`, I don't think there is a need to diffrentiate between two... Sorry for breaking you.
