### ISSUE TITLE
ON Statement issues

### ISSUE THREAD

**Issue by eglekaz** [usagi-coffee/tree-sitter-abl#83]
1. Keyword NEW is parsed as NE and W.
2. Keyword OLD is causing an error.

Example: 
```
ON WRITE OF Customer NEW new-cust OLD old-cust DO:
     a += 3.
END.
```

Reference:
https://documentation.progress.com/output/ua/OpenEdge_latest/pdsoe/PLUGINS_ROOT/com.openedge.pdt.langref.help/rfi1424920563735.html

**Comment by jkbz64** [comment]
33973500489c7d918a33dccb399491726bde65a2 fixed only issue .2, first one is a duplicate of #53

**Comment by jkbz64** [comment]
note that on_statement is still not fully implemented, would need more examples of complicated ones, OR's and revert blocks...
