### ISSUE TITLE
Whitespace change is causing issues

### ISSUE THREAD

**Issue by eglekaz** [usagi-coffee/tree-sitter-abl#87]
With recent release we have faced many issues regarding dots in various places in the code. We think that it might be caused by this commit: https://github.com/usagi-coffee/tree-sitter-abl/commit/5d401a2e56631ba028d57e20c9c38da9f4fa1076

Would it be possible to revert this change?

**Comment by jkbz64** [comment]
It was there for a reason, huh... will revert.
